listado=[["XV","Arica","Arica","Camarones","General Lagos","Putre"],
         ["I","Tarapacá","Alto Hospicio","Camiña","Colchane","Huara","Iquique","Pica","Pozo Almonte"],
         ["II","Antofagasta","Antofagasta","Calama","María Elena","Mejillones","Ollagüe","San Pedro de Atacama","Sierra Gorda","Taltal","Tocopilla"],
         ["III","Atacama","Alto del Carmen","Caldera","Chañaral","Copiapó","Diego de Almagro","Freirina","Huasco","Tierra Amarilla","Vallenar"],
         ["IV","Coquimbo","Andacollo","Canela","Combarbalá","Coquimbo","Illapel","La Higuera","La Serena","Los Vilos","Monte Patria","Ovalle","Paihuano","Punitaqui","Río Hurtado","Salamanca","Vicuña"],
         ["V","Valparaíso","Algarrobo","Cabildo","Calle Larga","Cartagena","Casablanca","Catemu","Concón","El Quisco","El Tabo","Hijuelas","Isla de Pascua","Juan Fernández","La Calera","La Cruz","La Ligua","Limache","Llaillay","Los Andes","Nogales","Olmué","Panquehue","Papudo","Petorca","Puchuncaví","Putaendo","Quillota","Quilpué","Quintero","Rinconada","San Antonio","San Esteban","San Felipe","Santa María","Santo Domingo","Valparaíso","Villa Alemana","Viña del Mar","Zapallar"],
         ["RM","Santiago","Alhué", "Buin", "Calera de Tango", "Cerrillos", "Cerro Navia", "Colina", "Conchalí", "Curacaví", "El Bosque", "El Monte", "Estación Central", "Huechuraba", "Independencia", "Isla de Maipo", "La Cisterna", "La Florida", "La Granja", "Lampa", "La Pintana", "La Reina", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado", "Macul", "Maipú", "María Pinto", "Melipilla", "Ñuñoa" "Padre Hurtado", "Paine", "Pedro Aguirre Cerda", "Peñaflor", "Peñalolén", "Pirque", "Providencia", "Pudahuel", "Puente Alto", "Quilicura", "Quinta Normal", "Recoleta", "Renca", "San Bernardo", "San Joaquín", "San José de Maipo", "San Miguel", "San Pedro", "San Ramón", "Santiago", "Talagante", "Tiltil", "Vitacura"],
         ["VI","Higgins","Chépica", "Chimbarongo", "Codegua", "Coinco", "Coltauco", "Doñihue", "Graneros", "La Estrella", "Las Cabras", "Litueche", "Lolol", "Machalí", "Malloa", "Marchihue", "Mostazal", "Nancagua", "Navidad", "Olivar", "Palmilla", "Paredones", "Peralillo", "Peumo", "Pichidegua", "Pichilemu", "Placilla", "Pumanque", "Quinta de Tilcoco", "Rancagua", "Rengo", "Requínoa", "San Fernando", "Santa Cruz", "San Vicente"],
         ["VII","Maule","Cauquenes", "Chanco", "Colbún", "Constitución", "Curepto", "Curicó", "Empedrado", "Hualañé", "Licantén", "Linares", "Longaví", "Maule", "Molina", "Parral", "Pelarco", "Pelluhue", "Pencahue", "Rauco", "Retiro", "Río Claro", "Romeral", "Sagrada Familia", "San Clemente", "San Javier", "San Rafael", "Talca", "Teno", "Vichuquén", "Villa Alegre", "Yerbas Buenas"],
         ["XVI","Ñuble","Bulnes", "Chillán", "Chillán Viejo", "Cobquecura", "Coelemu", "Coihueco", "El Carmen", "Ninhue", "Ñiquén", "Pemuco", "Pinto", "Portezuelo", "Quillón", "Quirihue", "Ránquil", "San Carlos", "San Fabián", "San Ignacio", "San Nicolás", "Treguaco", "Yungay"],
         ["VIII","Biobío","Alto Biobío", "Antuco", "Arauco", "Cabrero", "Cañete", "Chiguayante", "Concepción", "Contulmo", "Coronel", "Curanilahue", "Florida", "Hualpén", "Hualqui", "Laja", "Lebu", "Los Alamos", "Los Angeles", "Lota", "Mulchén", "Nacimiento", "Negrete", "Penco", "Quilaco", "Quilleco", "San Pedro de la Paz", "San Rosendo", "Santa Bárbara", "Santa Juana", "Talcahuano", "Tirúa", "Tomé", "Tucapel", "Yumbel"],
         ["IX","Araucanía","Angol", "Carahue", "Cholchol", "Collipulli", "Cunco", "Curacautín", "Curarrehue", "Ercilla", "Freire", "Galvarino", "Gorbea", "Lautaro", "Loncoche", "Lonquimay", "Los Sauces", "Lumaco", "Melipeuco", "Nueva Imperial", "Padre Las Casas", "Perquenco", "Pitrufquén", "Pucón", "Purén", "Renaico", "Saavedra", "Temuco", "Teodoro Schmidt", "Toltén", "Traiguén", "Victoria", "Vilcún", "Villarrica"],
         ["XIV","Los Ríos","Corral", "Futrono", "Lago Ranco", "Lanco", "La Unión", "Los Lagos", "Máfil", "Mariquina", "Paillaco", "Panguipulli", "Río Bueno", "Valdivia"],
         ["X","Los Lagos","Ancud", "Calbuco", "Castro", "Chaitén", "Chonchi", "Cochamó", "Curaco de Vélez", "Dalcahue", "Fresia", "Frutillar", "Futaleufú", "Hualaihué", "Llanquihue", "Los Muermos", "Maullín", "Osorno", "Palena", "Puerto Montt", "Puerto Octay", "Puerto Varas", "Puqueldón", "Purranque", "Puyehue", "Queilén", "Quellón", "Quemchi", "Quinchao", "Río Negro", "San Juan de la Costa", "San Pablo"],
         ["XI","Aysén","Aysén", "Chile Chico", "Cisnes", "Cochrane", "Coyhaique", "Guaitecas", "Lago Verde", "O'Higgins", "Río Ibáñez", "Tortel"],
         ["XII","Magallanes","Antártica", "Cabo de Hornos", "Laguna Blanca", "Natales", "Porvenir", "Primavera", "Punta Arenas", "Río Verde", "San Gregorio", "Timaukel", "Torres del Paine"],
['00', 'ASUNCION', 'ASUNCION'],
['01', 'CONCEPCION', 'CONCEPCION', 'BELEN', 'HORQUETA', 'LORETO', 'SAN CARLOS DEL APA', 'SAN LAZARO', 'YBY YAU', "AZOTE'Y", 'SARGENTO JOSE FELIX LOPEZ', 'SAN ALFREDO', 'PASO BARRETO', 'ARROYITO', 'PASO HORQUETA', 'ITACUA'],
['02', 'SAN PEDRO', 'SAN PEDRO DEL YCUAMANDYYU', 'ANTEQUERA', 'CHORE', 'GENERAL ELIZARDO AQUINO', 'ITACURUBI DEL ROSARIO', 'LIMA', 'NUEVA GERMANIA', 'SAN ESTANISLAO', 'SAN PABLO', 'TACUATI', 'UNION', '25 DE DICIEMBRE', 'VILLA DEL ROSARIO', 'GENERAL FRANCISCO ISIDORO RESQUIN', 'YATAITY DEL NORTE', 'GUAJAYVI', 'CAPIIBARY', 'SANTA ROSA DEL AGUARAY', 'YRYBUCUA', 'LIBERACION', 'SAN VICENTE PANCHOLO', 'SAN JOSE DEL ROSARIO'],
['03', 'CORDILLERA', 'CAACUPE', 'ALTOS', 'ARROYOS Y ESTEROS', 'ATYRA', 'CARAGUATAY', 'EMBOSCADA', 'EUSEBIO AYALA', 'ISLA PUCU', 'ITACURUBI DE LA CORDILLERA', 'JUAN DE MENA', 'LOMA GRANDE', 'MBOCAYATY DEL YHAGUY', 'NUEVA COLOMBIA', 'PIRIBEBUY', 'PRIMERO DE MARZO', 'SAN BERNARDINO', 'SANTA ELENA', 'TOBATI', 'VALENZUELA', 'SAN JOSE OBRERO'],
['04', 'GUAIRA', 'VILLARRICA', 'BORJA', 'CAPITAN MAURICIO JOSE TROCHE', 'CORONEL MARTINEZ', 'FELIX PEREZ CARDOZO', 'GRAL. EUGENIO A. GARAY', 'COLONIA INDEPENDENCIA', 'ITAPE', 'ITURBE', 'JOSE FASSARDI', 'MBOCAYATY', 'NATALICIO TALAVERA', 'ÑUMI', 'SAN SALVADOR', 'YATAITY', 'DOCTOR BOTTRELL', 'PASO YOBAI', 'TEBICUARY'],
['05', 'CAAGUAZU', 'CORONEL OVIEDO', 'CAAGUAZU', 'CARAYAO', 'DR. CECILIO BAEZ', 'SANTA ROSA DEL MBUTUY', 'DR. JUAN MANUEL FRUTOS', 'REPATRIACION', 'NUEVA LONDRES', 'SAN JOAQUIN', 'SAN JOSE DE LOS ARROYOS', 'YHU', 'DR. J. EULOGIO ESTIGARRIBIA', 'R.I. 3 CORRALES', 'RAUL ARSENIO OVIEDO', 'JOSE DOMINGO OCAMPOS', 'MARISCAL FRANCISCO SOLANO LOPEZ', 'LA PASTORA', '3 DE FEBRERO', 'SIMON BOLIVAR', 'VAQUERIA', 'TEMBIAPORA', 'NUEVA TOLEDO'],
['06', 'CAAZAPA', 'CAAZAPA', 'ABAI', 'BUENA VISTA', 'DR. MOISES S. BERTONI', 'GRAL. HIGINIO MORINIGO', 'MACIEL', 'SAN JUAN NEPOMUCENO', 'TAVAI', 'YEGROS', 'YUTY', '3 DE MAYO'],
['07', 'ITAPUA', 'ENCARNACION', 'BELLA VISTA', 'CAMBYRETA', 'CAPITAN MEZA', 'CAPITAN MIRANDA', 'NUEVA ALBORADA', 'CARMEN DEL PARANA', 'CORONEL BOGADO', 'CARLOS ANTONIO LOPEZ', 'NATALIO', 'FRAM', 'GENERAL ARTIGAS', 'GENERAL DELGADO', 'HOHENAU', 'JESUS', 'JOSE LEANDRO OVIEDO', 'OBLIGADO', 'MAYOR JULIO DIONISIO OTA??O', 'SAN COSME Y DAMIAN', 'SAN PEDRO DEL PARANA', 'SAN RAFAEL DEL PARANA', 'TRINIDAD', 'EDELIRA', 'TOMAS ROMERO PEREIRA', 'ALTO VERA', 'LA PAZ', 'YATYTAY', 'SAN JUAN DEL PARANA', 'PIRAPO', 'ITAPUA POTY'],
['08', 'MISIONES', 'SAN JUAN BAUTISTA DE LAS MISIONES', 'AYOLAS', 'SAN IGNACIO', 'SAN MIGUEL', 'SAN PATRICIO', 'SANTA MARIA', 'SANTA ROSA', 'SANTIAGO', 'VILLA FLORIDA', 'YABEBYRY'],
['09', 'PARAGUARI', 'PARAGUARI', 'ACAHAY', 'CAAPUCU', 'CABALLERO', 'CARAPEGUA', 'ESCOBAR', 'LA COLMENA', 'MBUYAPEY', 'PIRAYU', 'QUIINDY', 'QUYQUYHO', 'ROQUE GONZALEZ DE SANTA CRUZ', 'SAPUCAI', 'TEBICUARY-MI', 'YAGUARON', 'YBYCUI', 'YBYTYMI', 'MARIA ANTONIA'],
['10', 'ALTO PARANA', 'CIUDAD DEL ESTE', 'PRESIDENTE FRANCO', 'DOMINGO MARTINEZ DE IRALA', 'DR. JUAN LEON MALLORQUIN', 'HERNANDARIAS', 'ITAKYRY', "JUAN E. O'LEARY", 'ÑACUNDAY', 'YGUAZU', 'LOS CEDRALES', 'MINGA GUAZU', 'SAN CRISTOBAL', 'SANTA RITA', 'NARANJAL', 'SANTA ROSA DEL MONDAY', 'MINGA PORA', 'MBARACAYU', 'SAN ALBERTO', 'IRUÑA', 'SANTA FE DEL PARANA', 'TAVAPY', 'DR. RAUL PE?A'],
['11', 'CENTRAL', 'AREGUA', 'CAPIATA', 'FERNANDO DE LA MORA', 'GUARAMBARE', 'ITA', 'ITAUGUA', 'LAMBARE', 'LIMPIO', 'LUQUE', 'MARIANO ROQUE ALONSO', 'NUEVA ITALIA', 'ÑEMBY', 'SAN ANTONIO', 'SAN LORENZO', 'VILLA ELISA', 'VILLETA', 'YPACARAI', 'YPANE', 'J. AUGUSTO SALDIVAR'],
['12', 'ÑEEMBUCU', 'PILAR', 'ALBERDI', 'CERRITO', 'DESMOCHADOS', 'GRAL. JOSE EDUVIGIS DIAZ', 'GUAZU CUA', 'HUMAITA', 'ISLA UMBU', 'LAURELES', 'MAYOR JOSE DE JESUS MARTINEZ', 'PASO DE PATRIA', 'SAN JUAN BAUTISTA DE ÑEEMBUCU', 'TACUARAS', 'VILLA FRANCA', 'VILLA OLIVA', 'VILLALBIN'],
['13', 'AMAMBAY', 'PEDRO JUAN CABALLERO', 'BELLA VISTA', 'CAPITAN BADO', 'ZANJA PYTA', 'KARAPAI', 'CERRO CORA'],
['14', 'CANINDEYU', 'SALTO DEL GUAIRA', 'CORPUS CHRISTI', 'VILLA CURUGUATY', 'VILLA YGATIMI', 'ITANARA', 'YPEJHU', 'FRANCISCO CABALLERO ALVAREZ', 'KATUETE', 'LA PALOMA DEL ESPIRITU SANTO', 'NUEVA ESPERANZA', 'YASY KAÃ‘Y', 'YBYRAROBANA', 'YBY PYTA', 'MARACANA', 'PUERTO ADELA', 'LAUREL'],
['15', 'PRESIDENTE HAYES', 'BENJAMIN ACEVAL', 'PUERTO PINASCO', 'VILLA HAYES', 'NANAWA', 'JOSE FALCON', 'TTE 1RO MANUEL IRALA FERNANDEZ', 'TENIENTE ESTEBAN MARTINEZ', 'GENERAL JOSE MARIA BRUGUEZ', 'CAMPO ACEVAL', 'NUEVA ASUNCION'],
['16', 'BOQUERON', 'MARISCAL JOSE FELIX ESTIGARRIBIA', 'FILADELFIA', 'LOMA PLATA', 'BOQUERON'],
['17', 'ALTO PARAGUAY', 'FUERTE OLIMPO', 'PUERTO CASADO', 'BAHIA NEGRA', 'CARMELO PERALTA'],
         ]
def normalize_string(s):
    return unicodedata.normalize('NFD', s).encode('ascii', 'ignore').decode('utf-8').lower()
Region=datos_empresas["Lugar"].iloc[datos_empresas_index]
for comunas in listado:
    if any(normalize_string(item) == normalize_string(Region) for item in comunas):
        Region=comunas[0]


